2021-11-17 11:18:37,680: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 11:18:41,048: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 11:18:41,102: logger Qinstrument.Qlaser: file lasers.py: line 253 WARNING: Already connected to laser!
2021-11-17 12:10:57,729: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 12:11:01,840: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 12:11:01,873: logger Qinstrument.Qlaser: file lasers.py: line 252 ERROR: 7
2021-11-17 12:15:52,225: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 12:15:55,679: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 13:48:08,228: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 13:48:10,946: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 13:48:10,952: logger Qinstrument.Qlaser: file lasers.py: line 252 ERROR: Could not connect to laser - 7
2021-11-17 13:50:23,026: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 13:50:29,427: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 13:57:59,874: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 14:06:28,581: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 14:06:32,355: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 14:36:33,256: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 14:36:35,615: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 14:38:29,322: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 14:38:31,714: logger Qinstrument.Qlaser: file lasers.py: line 243 INFO: connecting to laser
2021-11-17 14:38:31,722: logger Qinstrument.Qlaser: file lasers.py: line 252 ERROR: Could not connect to laser Laser - Failed to connect
2021-11-17 14:41:47,134: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-17 14:41:50,484: logger Qinstrument.Qlaser: file lasers.py: line 246 INFO: connecting to laser
2021-11-17 14:41:50,493: logger Qinstrument.Qlaser: file lasers.py: line 230 ERROR: Laser - Failed to connect
2021-11-18 13:22:48,417: logger Qinstrument.Qlaser: file lasers.py: line 45 INFO: init laser
2021-11-18 13:22:51,715: logger Qinstrument.Qlaser: file lasers.py: line 246 INFO: connecting to laser
2021-11-18 13:22:51,723: logger Qinstrument.Qlaser: file lasers.py: line 230 ERROR: Laser - Failed to connect
